FROM node:18-alpine

WORKDIR /app

# Installer Ember CLI globalement
RUN npm install -g ember-cli@5.5.0

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

EXPOSE 4200

CMD ["ember", "serve", "--host", "0.0.0.0", "--port", "4200"]