version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: green-taxo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-greentaxo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-greentaxo_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - green-taxo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-greentaxo} -d ${POSTGRES_DB:-greentaxo_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis pour Celery
  redis:
    image: redis:7-alpine
    container_name: green-taxo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - green-taxo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-taxo-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-greentaxo}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-greentaxo_db}
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      DEBUG: ${DEBUG:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_cache:/root/.cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - green-taxo-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-taxo-celery-worker
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-greentaxo}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-greentaxo_db}
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY:-}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      DEBUG: ${DEBUG:-true}
    volumes:
      - ./backend:/app
      - backend_cache:/root/.cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - green-taxo-network
    command: celery -A app.celery_app worker --loglevel=info

  # Celery Flower (monitoring optionnel)
  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-taxo-flower
    restart: unless-stopped
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    networks:
      - green-taxo-network
    command: celery -A app.celery_app flower --port=5555

  # Frontend Ember.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: green-taxo-frontend
    restart: unless-stopped
    environment:
      API_HOST: ${API_HOST:-http://localhost:8000}
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
      - /app/tmp
    depends_on:
      - backend
    networks:
      - green-taxo-network
    command: npm start

networks:
  green-taxo-network:
    driver: bridge

volumes:
  postgres_data:
  backend_cache: